#!/usr/bin/bash
set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")"
source ./config
config "$@"

if [[ -S "$SOCKET" ]]; then
    echo Already started on port $PORT
    exit
fi

ssh -R $PORT:localhost:$PORT -M -S "$SOCKET" -fNT "$DOMAIN"
echo Started on port $PORT
