#!/usr/bin/bash
set -euo pipefail

if [[ $# -ne 1 ]]
then
    printf "%s\n" "Usage: $0 <your-domain>"
    exit 1
fi

DOMAIN="$1"
CONFIG="$HOME/.procto/$DOMAIN.conf"
if [[ ! -f "$CONFIG" ]]
then
    printf "%s\n" "Config $CONFIG not found"
    exit 1
fi

source "$CONFIG"
PORT=$(./port "$DOMAIN")
SOCKET="/tmp/$DOMAIN-$PORT-socket"

if [[ -S "$SOCKET" ]]; then
    echo Already started on port $PORT
    exit
fi

ssh -R $PORT:localhost:$PORT -M -S "$SOCKET" -fNT "$DOMAIN"
echo Started on port $PORT
