#!/usr/bin/bash
set -euo pipefail

cd "$(dirname "$0")"
source ./config
config "$@"

if [[ -S "$SOCKET" ]]; then
    echo Already started on port $PORT
    exit
fi

ssh -R $PORT:localhost:$PORT -M -S "$SOCKET" -fNT "$SSH_USER@$DOMAIN"
echo Started on port $PORT
