#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/procto-lib"
config "$@"

commands="""
set -euo pipefail
apt-get remove -qy apache2
apt-get install -qy nginx certbot python3-certbot-nginx
certbot certonly --non-interactive --agree-tos --email $EMAIL --nginx -d $DOMAIN
rm -rf /etc/nginx/sites-enabled/default
cat > /etc/nginx/sites-enabled/procto-$DOMAIN.conf
service nginx restart
"""

nginx_config="""
server {
    listen 443 ssl;
    server_name $DOMAIN;
    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    location / {
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Scheme https;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_pass http://localhost:$PORT/;
    }
}
"""

# shellcheck disable=SC2029
ssh "$SSH_USER@$DOMAIN" "$commands" <<< "$nginx_config"
