#!/usr/bin/bash
set -euo pipefail

if [[ $# -ne 1 ]]
then
    echo Usage: $0 name
    exit 1
fi

config="$HOME/.procto/$1.conf"
if [[ ! -f "$config" ]]
then
    echo Config not found
    exit 1
fi

source "$config"
PORT=$(./port "$DOMAIN")
SOCKET="/tmp/$DOMAIN-$PORT-socket"

if [[ -S "$SOCKET" ]]; then
    echo Already started on port $PORT
    exit
fi

ssh -R $PORT:localhost:$PORT -M -S "$SOCKET" -fNT "$DOMAIN"
echo Started on port $PORT
